Add ncu

diff --git a/.github/workflows/nvidia_workflow.yml b/.github/workflows/nvidia_workflow.yml
--- a/.github/workflows/nvidia_workflow.yml
+++ b/.github/workflows/nvidia_workflow.yml
@@ -28,6 +28,11 @@ jobs:
       shell: bash
       run: |
         nvidia-smi || echo "nvidia-smi failed"
+    
+    - name: ncu
+      shell: bash
+      run: |
+        ncu --version || echo "ncu failed"
 
     - name: Create input files
       shell: bash
